### ISSUE TITLE
Use kebab-case?

### ISSUE THREAD

**Issue by bntzio** [paulmolluzzo/convert-css-in-js#4]
Hey Paul good work on this code extension! 👍 

Is there a way to disable camelCase and just use kebab-case in my css-in-js files?

The thing is, `styled-components` use normal css styles.

Thanks! 😄

**Comment by paulmolluzzo** [comment]
@bntzio 🙌 

There's no settings or anything, so the real way to do it would be to check scope, but the extension doesn't currently do that.

I haven't used it, but this extension is specifically created for styled-component syntax, so you might want to take a look: https://github.com/Microsoft/typescript-styled-plugin

Last, for future reference this repo is deprecated since the project was moved into another project: https://github.com/ansumanshah/css-in-js. If you happen to dig into the code and want to submit a PR to support styled-components, that's where to do it.

Other than that there's not much I can do here so I'm going to close the issue. Feel free to move it over to the other repo, try the extension I linked, or comment here with any other thoughts.
